# Устанавливаем базовый образ PHP
FROM php:8.3-fpm

# Установка утилиты unzip
RUN apt update && apt install -y unzip mc

# Устанавливаем необходимые расширения PHP
RUN docker-php-ext-install pdo pdo_mysql

# Установка Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Установка дополнительных расширений PHP для Redis
RUN pecl install redis && docker-php-ext-enable redis

# Устанавливаем рабочую директорию
WORKDIR /var/www/html
# Копирование и установка зависимостей PHP
COPY src /var/www/html
RUN composer install

# Установка supervisord
RUN apt-get install -y supervisor

# Копирование конфигурационного файла supervisord для воркеров очереди
COPY supervisor_api.conf /etc/supervisor/conf.d/supervisord.conf

# Открываем порт для доступа к приложению
EXPOSE 8000

# Запуск сервисов контейнера
CMD ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
